name: streamify
description: Simple state management for Flutter.
version: 0.2.0
repository: https://github.com/alselawi/streamify

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0